// {
// 	eng: "search1",
// 	odia: " ାସ,daughter ିଅ,   ି",divine, ଦୁ  ,understand ି ,to ଼ା,  ଣ,ଭଗବାନ,purgatory-ପାପ ପରିଶୋଧ ନିବାସ,  ଶ୍ବର, , ଶବ୍ଦ - Word - ବାକ୍ୟ, THOU- ତୁମ୍ଭଭେ, season, Russia - ରୁଷିଆ, jezebel - ଇଷେବଲ, ମେଷ - sheep, ଆଦ - ଆଦୌ, get reach - ପହଞ୍ଚିବା,ବିଶ୍ ,ଗୌ ଼ୁ, glory, ory,health - ସ୍ୱାସ୍ଥ୍ୟ,offer -ନୈ, restore -ପୁନର୍ସ୍ଥାପିତ,ପୁନର୍ସ୍ଥାପନ , meeting , pour, raise,running,
// ଧର୍ମଶାସ୍ତ୍ର -theology, doctrine - ଉପଦେଶ, ଯୌନ  -sex, bishop - ବିଶପ୍, , read,reading ଼ୁ,privilege,to ି,explained ା,fighting ୁ,scient,
// intell,,imb, calling - ଆହ୍ୱାନ, run,live - ବଞ୍ଚିବ,malachi-ମାଲାକ୍ଷି ,,army,accept,recogni - ସ୍ୱୀକାର,  firm,  , GENERATION,,  ାରା - ଦ୍ୱାରା,::, ଶ୍ୱର,Elohim - ଏଲୋହୀମ,cow , chronicles - ବଂଶାବଳୀ
// ତ୍ୱ,five - ପାଞ୍ଚ,, ସେଣ୍ଟ - ସାଧୁ, ଜ୍ଞାନୀ- wise ଜ୍ ,ଦୁ -  ଦୁଃ, altar - ଯଜ୍ଞବେଦି,  ଣ - କୌ ,Esau - ଏଷୌ, ଓ Oh,},

// ଦୁଃ ତଃ ଦ୍ୱା ୱା ଇ  ରୄୃ ଝ ଝି ଢ଼ି ଝୁ  ଝା ଢ଼ୁ ଢ଼ା   ଢ଼େ ଭେ ନୈ  ଶୈ ଦୈ ବୈ  ସୈ  ମୌ  ଦୌ ଗୌ ସୌ  ଲୌ କୌ ଢ଼ା  ପ୍ରତିଜ୍ଞା  ଦ୍ୱାରା ବିଶ୍ୱାସ ପରମେଶ୍ବର  ମେଷ  ଦିବ୍ୟାଶ୍ୱରୀୟ ଟେପ୍ଉପରେ ଖାଲି ସ୍ଥାନ ଦ୍ୱାରା ନାଳ ଧରର୍ଯ୍ୟର   ଷୌ ଇଷେବଲ

export const common_phrases = [
	{
		eng: "God",
		odia: "ପରମେଶ୍ବର",
	},
	{
		eng: "Jesus Christ",
		odia: "ଯୀଶୁ ଖ୍ରୀଷ୍ଟ",
	},
	{ eng: "rapture", odia: "ରାପ୍ଟର" },
	{
		eng: "believer",
		odia: "ବିଶ୍ୱାସୀ",
	},
	{
		eng: "Blank.spot.on.tape",
		odia: "ଟେପ୍ଉପରେ ଖାଲି ସ୍ଥାନ",
	},
	{
		eng: "privilege",
		odia: "ସୁବିଧା",
	},
	{
		eng: "reading",
		odia: "ପଢିବା",
	},
	{
		eng: "somewhere",
		odia: "କୌଣସି",
	},
	{
		eng: "divine",
		odia: "ଦିବ୍ୟାଶ୍ୱରୀୟ",
	},
	{
		eng: "by",
		odia: "ଦ୍ୱାରା",
	},
	{
		eng: "ethics",
		odia: "ଏଥିକ୍ସ",
	},
	{
		eng: "promise",
		odia: "ପ୍ରତିଜ୍ଞା",
	},
	{
		eng: "patience",
		odia: "ଧରର୍ଯ୍ୟର",
	},
	{
		eng: "calling",
		odia: "ଆୱାନ୍",
	},
	{
		eng: "vindicate",
		odia: "ବ୍ୟାଖ୍ୟା",
	},
	{
		eng: "living",
		odia: "ବଞ୍ଚୁଛୁ",
	},
	{
		eng: "prophets",
		odia: "ଭବିଷ୍ୟ‌ଦ୍‌ବକ୍ତାମାନଙ୍କ",
	},
	{
		eng: "prophet",
		odia: "ଭବିଷ୍ୟ‌ଦ୍‌ବକ୍ତା",
	},
	{
		eng: "come down",
		odia: "ଓହ୍ଲାଇଲେ",
	},
	{
		eng: "reading",
		odia: "ପଢ଼ିବା",
	},
	{
		eng: "church",
		odia: "ଚର୍ଚ୍ଚ",
	},
	{
		eng: "Laodicean Church Age",
		odia: "ଲାଓଡିକିଆ ଚର୍ଚ୍ଚ ଯୁଗ",
	},
	{
		eng: "Christians",
		odia: "ଖ୍ରୀଷ୍ଟିଆନମାନେ",
	},
	{
		eng: "Amen",
		odia: "ଆମେନ୍",
	},
	{
		eng: "or",
		odia: "କିମ୍ବା",
	},
	{
		eng: "code",
		odia: "କୋଡ୍",
	},
	{
		eng: "Word of God",
		odia: "ପରମେଶ୍ବରଙ୍କ ବାକ୍ୟ",
	},
	{
		eng: "generation",
		odia: "ପିଢି଼",
	},
	{
		eng: "immoral",
		odia: "ଅନୈତିକ",
	},
	{
		eng: "sheep",
		odia: "ମେଷ",
	},
	{
		eng: "fundamental",
		odia: "ମୌଳିକ",
	},
	{
		eng: "world",
		odia: "ବିଶ୍ବର",
	},
	{
		eng: "supernatural",
		odia: "ଅଲୌକିକ",
	},
];
export const oriya_keys = {
	oriya_alphabets_set1: {
		କ: "ka",
		ଖ: "kha",
		ଗ: "ga",
		ଘ: "gha",
		ଙ: "nga",
		ଚ: "ca",
		ଛ: "cha",
		ଜ: "ja",
		ଝ: "jha",
		ଞ: "ña",
		ଟ: "Ṭa",
		ଠ: "Ṭha",
		ଡ: "Ḍa",
		ଢ: "Ḍha",
		ଣ: "Ṇa",
		ତ: "ta",
		ଥ: "tha",
		ଦ: "da",
		ଧ: "dha",
		ନ: "na",
		ପ: "pa",
		ଫ: "pha",
		ବ: "ba",
		ଭ: "bha",
		ମ: "ma",
		ଯ: "ya",
		ର: "ra",
		ଲ: "la",
		ଳ: "Ḷa",
		ଵ: "va",
		ଶ: "śa",
		ଷ: "Ṣa",
		ସ: "sa",
		ହ: "ha",
		ୟ: "Ya",
		ଡ଼: "Ṛa",
		ଢ଼: "Ṛha",
		ୱ: "wa",
	},
	oriya_alphabets_set2: {
		set1: {
			ଅ: "a",
			ଆ: "ā",
			ଇ: "i",
			ଈ: "ī",
			ଉ: "u",
			ଊ: "ū",
		},
		set2: {
			"ା": "ା",
			"ି": "ି",
			"ୀ": "ୀ",
			"ୁ": "ୁ",
			"ୂ": "ୂ",
		},
		set3: {
			ଋ: "ri",
			ୠ: "rī",
			ଌ: "li",
			ୡ: "lī",
		},
		set4: {
			"ୃ": "ୃ",
			"ୄ": "ୄ",
			"ୢ": "ୢ",
			"ୣ": "ୣ",
			"୍": "୍",
		},
		set5: {
			"ଂ": "ଂ",
			"ଃ": "ଃ",
			"଼": "଼",
			ଽ: "ଽ",
		},
		set6: {
			0: "୦",
			1: "୧",
			2: "୨",
			3: "୩",
			4: "୪",
			5: "୫",
			6: "୬",
			7: "୭",
			8: "୮",
			9: "୯",
		},
		set7: {
			ଏ: "e",
			ଐ: "ai",
			ଓ: "o",
			ଔ: "au",
		},
		set8: {
			"େ": "େ",
			"ୈ": "ୈ",
			"ୋ": "ୋ",
			"ୌ": "ୌ",
		},
		set9: {
			"ୖ": "ୖ",
			"ୣୗ": "ୣୗ",
		},
	},
};

// punctuation: {
//   comma: ",",
//   full_stop: ".",
//   question_mark: "?",
//   exclamation_mark: "!",
//   semicolon: ";",
//   colon: ":",
//   ellipsis: "…",
//   hyphen: "-",
//   en_dash: "–",
//   em_dash: "—",
//   single_quotation_mark: "'",
//   double_quotation_mark: '"',
//   parentheses: "()",
//   square_brackets: "[]",
//   curly_brackets: "{}",
//   angle_brackets: "<>",
//   slash: "/",
//   backslash: "\\",
//   ampersand: "&",
//   asterisk: "*",
//   hash: "#",
//   percent: "%",
//   caret: "^",
//   underscore: "_",
//   at_sign: "@",
//   dollar_sign: "$",
//   plus_sign: "+",
//   minus_sign: "-",
//   equals_sign: "=",
//   vertical_bar: "|",
//   tilde: "~",
//   grave_accent: "`",
// },
